server:
  port: 8090

spring:
  application:
    name: abms-apigateway

  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: http://localhost:8092
          predicates:
            - Path=/patient/**
        - id: clinic-service
          uri: http://localhost:8091
          predicates:
            - Path=/clinic/**
        - id: notification-service
          uri: http://localhost:8093
          predicates:
            - Path=/notification/**
